name: trigger jenkins job
on: [push]
jobs:
  sonarqube-trigger-push:    
    runs-on: windows-latest
    steps:
    - name: Trigger jenkins job
      uses: ykerkeni/sonarqube-scan-action-windows@main      
        
